[project]
name = "peru-budget-lakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "connectorx>=0.4.5",
    "dotenv>=0.9.9",
    "duckdb>=1.5.2",
    "ipykernel>=7.2.0",
    "notebook>=7.5.6",
    "polars>=1.40.1",
    "pyarrow>=24.0.0",
]
